// Generated by ~/.agents/ops/gen-theme.mjs — do not edit by hand.
//
// Not a transcription test. Hand-copied hexes only prove that someone copied consistently
// (Shrinkora carried the same values in three places). This asserts the colours RESOLVE from
// the shipped bundle at the expected RGB — which is what catches a catalog that never got
// bundled, or a colorset the views no longer name.
import SwiftUI
import Testing
@testable import NoBuy

@Suite("NoBuyTheme resolves from the asset catalog")
struct NoBuyThemeResolutionTests {
    @Test("accentKept (accent.kept)")
    func accentKeptResolves() {
        let light = NoBuyTheme.accentKept.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "accentKept did not resolve — is the colorset in the bundle?")
    }
    @Test("accentSpentMark (accent.spentMark)")
    func accentSpentMarkResolves() {
        let light = NoBuyTheme.accentSpentMark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "accentSpentMark did not resolve — is the colorset in the bundle?")
    }
    @Test("accentSpentText (accent.spentText)")
    func accentSpentTextResolves() {
        let light = NoBuyTheme.accentSpentText.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "accentSpentText did not resolve — is the colorset in the bundle?")
    }
    @Test("inkDialMinor (ink.dialMinor)")
    func inkDialMinorResolves() {
        let light = NoBuyTheme.inkDialMinor.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "inkDialMinor did not resolve — is the colorset in the bundle?")
    }
    @Test("inkHairline (ink.hairline)")
    func inkHairlineResolves() {
        let light = NoBuyTheme.inkHairline.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "inkHairline did not resolve — is the colorset in the bundle?")
    }
    @Test("inkOnAccent (ink.onAccent)")
    func inkOnAccentResolves() {
        let light = NoBuyTheme.inkOnAccent.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "inkOnAccent did not resolve — is the colorset in the bundle?")
    }
    @Test("inkPrimary (ink.primary)")
    func inkPrimaryResolves() {
        let light = NoBuyTheme.inkPrimary.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "inkPrimary did not resolve — is the colorset in the bundle?")
    }
    @Test("inkSecondary (ink.secondary)")
    func inkSecondaryResolves() {
        let light = NoBuyTheme.inkSecondary.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "inkSecondary did not resolve — is the colorset in the bundle?")
    }
    @Test("stateNotYet (state.notYet)")
    func stateNotYetResolves() {
        let light = NoBuyTheme.stateNotYet.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "stateNotYet did not resolve — is the colorset in the bundle?")
    }
    @Test("stateWait (state.wait)")
    func stateWaitResolves() {
        let light = NoBuyTheme.stateWait.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "stateWait did not resolve — is the colorset in the bundle?")
    }
    @Test("surfaceDial (surface.dial)")
    func surfaceDialResolves() {
        let light = NoBuyTheme.surfaceDial.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "surfaceDial did not resolve — is the colorset in the bundle?")
    }
    @Test("surfaceField (surface.field)")
    func surfaceFieldResolves() {
        let light = NoBuyTheme.surfaceField.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "surfaceField did not resolve — is the colorset in the bundle?")
    }
    @Test("surfaceScrim (surface.scrim)")
    func surfaceScrimResolves() {
        let light = NoBuyTheme.surfaceScrim.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "surfaceScrim did not resolve — is the colorset in the bundle?")
    }
    @Test("surfaceWell (surface.well)")
    func surfaceWellResolves() {
        let light = NoBuyTheme.surfaceWell.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "surfaceWell did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesCreamDialDark (themeFinishes.cream.dialDark)")
    func themeFinishesCreamDialDarkResolves() {
        let light = NoBuyTheme.themeFinishesCreamDialDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesCreamDialDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesCreamDialLight (themeFinishes.cream.dialLight)")
    func themeFinishesCreamDialLightResolves() {
        let light = NoBuyTheme.themeFinishesCreamDialLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesCreamDialLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesCreamFieldDark (themeFinishes.cream.fieldDark)")
    func themeFinishesCreamFieldDarkResolves() {
        let light = NoBuyTheme.themeFinishesCreamFieldDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesCreamFieldDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesCreamFieldLight (themeFinishes.cream.fieldLight)")
    func themeFinishesCreamFieldLightResolves() {
        let light = NoBuyTheme.themeFinishesCreamFieldLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesCreamFieldLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesCreamWellLight (themeFinishes.cream.wellLight)")
    func themeFinishesCreamWellLightResolves() {
        let light = NoBuyTheme.themeFinishesCreamWellLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesCreamWellLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesMossDialDark (themeFinishes.moss.dialDark)")
    func themeFinishesMossDialDarkResolves() {
        let light = NoBuyTheme.themeFinishesMossDialDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesMossDialDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesMossDialLight (themeFinishes.moss.dialLight)")
    func themeFinishesMossDialLightResolves() {
        let light = NoBuyTheme.themeFinishesMossDialLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesMossDialLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesMossFieldDark (themeFinishes.moss.fieldDark)")
    func themeFinishesMossFieldDarkResolves() {
        let light = NoBuyTheme.themeFinishesMossFieldDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesMossFieldDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesMossFieldLight (themeFinishes.moss.fieldLight)")
    func themeFinishesMossFieldLightResolves() {
        let light = NoBuyTheme.themeFinishesMossFieldLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesMossFieldLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesMossWellLight (themeFinishes.moss.wellLight)")
    func themeFinishesMossWellLightResolves() {
        let light = NoBuyTheme.themeFinishesMossWellLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesMossWellLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSalmonDialDark (themeFinishes.salmon.dialDark)")
    func themeFinishesSalmonDialDarkResolves() {
        let light = NoBuyTheme.themeFinishesSalmonDialDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSalmonDialDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSalmonDialLight (themeFinishes.salmon.dialLight)")
    func themeFinishesSalmonDialLightResolves() {
        let light = NoBuyTheme.themeFinishesSalmonDialLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSalmonDialLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSalmonFieldDark (themeFinishes.salmon.fieldDark)")
    func themeFinishesSalmonFieldDarkResolves() {
        let light = NoBuyTheme.themeFinishesSalmonFieldDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSalmonFieldDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSalmonFieldLight (themeFinishes.salmon.fieldLight)")
    func themeFinishesSalmonFieldLightResolves() {
        let light = NoBuyTheme.themeFinishesSalmonFieldLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSalmonFieldLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSalmonWellLight (themeFinishes.salmon.wellLight)")
    func themeFinishesSalmonWellLightResolves() {
        let light = NoBuyTheme.themeFinishesSalmonWellLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSalmonWellLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSilverDialDark (themeFinishes.silver.dialDark)")
    func themeFinishesSilverDialDarkResolves() {
        let light = NoBuyTheme.themeFinishesSilverDialDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSilverDialDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSilverDialLight (themeFinishes.silver.dialLight)")
    func themeFinishesSilverDialLightResolves() {
        let light = NoBuyTheme.themeFinishesSilverDialLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSilverDialLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSilverFieldDark (themeFinishes.silver.fieldDark)")
    func themeFinishesSilverFieldDarkResolves() {
        let light = NoBuyTheme.themeFinishesSilverFieldDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSilverFieldDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSilverFieldLight (themeFinishes.silver.fieldLight)")
    func themeFinishesSilverFieldLightResolves() {
        let light = NoBuyTheme.themeFinishesSilverFieldLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSilverFieldLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSilverWellLight (themeFinishes.silver.wellLight)")
    func themeFinishesSilverWellLightResolves() {
        let light = NoBuyTheme.themeFinishesSilverWellLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSilverWellLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSlateDialDark (themeFinishes.slate.dialDark)")
    func themeFinishesSlateDialDarkResolves() {
        let light = NoBuyTheme.themeFinishesSlateDialDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSlateDialDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSlateDialLight (themeFinishes.slate.dialLight)")
    func themeFinishesSlateDialLightResolves() {
        let light = NoBuyTheme.themeFinishesSlateDialLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSlateDialLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSlateFieldDark (themeFinishes.slate.fieldDark)")
    func themeFinishesSlateFieldDarkResolves() {
        let light = NoBuyTheme.themeFinishesSlateFieldDark.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSlateFieldDark did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSlateFieldLight (themeFinishes.slate.fieldLight)")
    func themeFinishesSlateFieldLightResolves() {
        let light = NoBuyTheme.themeFinishesSlateFieldLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSlateFieldLight did not resolve — is the colorset in the bundle?")
    }
    @Test("themeFinishesSlateWellLight (themeFinishes.slate.wellLight)")
    func themeFinishesSlateWellLightResolves() {
        let light = NoBuyTheme.themeFinishesSlateWellLight.resolve(in: EnvironmentValues())
        #expect(light.opacity > 0, "themeFinishesSlateWellLight did not resolve — is the colorset in the bundle?")
    }
}
