// Generated by ~/.agents/ops/gen-theme.mjs from tokens.json — do not edit by hand.
//
// Design tokens are the only source of colour. Views read these properties; no view may carry
// a hex literal. Regenerate after any token change; `design-preflight` fails the submit gate
// when the generated files no longer match the tokens.
import SwiftUI

public enum NoBuyTheme {
    /// `#33567E / #D3D8A4` — `accent.kept`
    public static let accentKept = Color("accentKept", bundle: .main)
    /// `#A65B41 / #C98F7D` — `accent.spentMark`
    public static let accentSpentMark = Color("accentSpentMark", bundle: .main)
    /// `#8F4A33 / #C98F7D` — `accent.spentText`
    public static let accentSpentText = Color("accentSpentText", bundle: .main)
    /// `#9AA09B / #5B615C` — `ink.dialMinor`
    public static let inkDialMinor = Color("inkDialMinor", bundle: .main)
    /// `#C4C8C3 / #2E3336` — `ink.hairline`
    public static let inkHairline = Color("inkHairline", bundle: .main)
    /// `#F4F5F1 / #0F1113` — `ink.onAccent`
    public static let inkOnAccent = Color("inkOnAccent", bundle: .main)
    /// `#24272B / #DDE0D8` — `ink.primary`
    public static let inkPrimary = Color("inkPrimary", bundle: .main)
    /// `#5C6165 / #9BA19D` — `ink.secondary`
    public static let inkSecondary = Color("inkSecondary", bundle: .main)
    /// `#C4C8C3 / #3C4245` — `state.notYet`
    public static let stateNotYet = Color("stateNotYet", bundle: .main)
    /// `#767B7E / #848B87` — `state.wait`
    public static let stateWait = Color("stateWait", bundle: .main)
    /// `#F4F5F1 / #171A1C` — `surface.dial`
    public static let surfaceDial = Color("surfaceDial", bundle: .main)
    /// `#E8EAE7 / #0F1113` — `surface.field`
    public static let surfaceField = Color("surfaceField", bundle: .main)
    /// `rgba(15,17,19,0.4) / rgba(0,0,0,0.55)` — `surface.scrim`
    public static let surfaceScrim = Color("surfaceScrim", bundle: .main)
    /// `#E0E3DF / #14171A` — `surface.well`
    public static let surfaceWell = Color("surfaceWell", bundle: .main)
    /// `#1A1915` — `themeFinishes.cream.dialDark`
    public static let themeFinishesCreamDialDark = Color("themeFinishesCreamDialDark", bundle: .main)
    /// `#F6F2E7` — `themeFinishes.cream.dialLight`
    public static let themeFinishesCreamDialLight = Color("themeFinishesCreamDialLight", bundle: .main)
    /// `#12110D` — `themeFinishes.cream.fieldDark`
    public static let themeFinishesCreamFieldDark = Color("themeFinishesCreamFieldDark", bundle: .main)
    /// `#EAE6DB` — `themeFinishes.cream.fieldLight`
    public static let themeFinishesCreamFieldLight = Color("themeFinishesCreamFieldLight", bundle: .main)
    /// `#E2DED2` — `themeFinishes.cream.wellLight`
    public static let themeFinishesCreamWellLight = Color("themeFinishesCreamWellLight", bundle: .main)
    /// `#171B16` — `themeFinishes.moss.dialDark`
    public static let themeFinishesMossDialDark = Color("themeFinishesMossDialDark", bundle: .main)
    /// `#F0F3EC` — `themeFinishes.moss.dialLight`
    public static let themeFinishesMossDialLight = Color("themeFinishesMossDialLight", bundle: .main)
    /// `#0F120E` — `themeFinishes.moss.fieldDark`
    public static let themeFinishesMossFieldDark = Color("themeFinishesMossFieldDark", bundle: .main)
    /// `#E2E7DF` — `themeFinishes.moss.fieldLight`
    public static let themeFinishesMossFieldLight = Color("themeFinishesMossFieldLight", bundle: .main)
    /// `#DAE0D6` — `themeFinishes.moss.wellLight`
    public static let themeFinishesMossWellLight = Color("themeFinishesMossWellLight", bundle: .main)
    /// `#1C1817` — `themeFinishes.salmon.dialDark`
    public static let themeFinishesSalmonDialDark = Color("themeFinishesSalmonDialDark", bundle: .main)
    /// `#F7F0EA` — `themeFinishes.salmon.dialLight`
    public static let themeFinishesSalmonDialLight = Color("themeFinishesSalmonDialLight", bundle: .main)
    /// `#131010` — `themeFinishes.salmon.fieldDark`
    public static let themeFinishesSalmonFieldDark = Color("themeFinishesSalmonFieldDark", bundle: .main)
    /// `#EBE2DC` — `themeFinishes.salmon.fieldLight`
    public static let themeFinishesSalmonFieldLight = Color("themeFinishesSalmonFieldLight", bundle: .main)
    /// `#E3DAD3` — `themeFinishes.salmon.wellLight`
    public static let themeFinishesSalmonWellLight = Color("themeFinishesSalmonWellLight", bundle: .main)
    /// `#171A1C` — `themeFinishes.silver.dialDark`
    public static let themeFinishesSilverDialDark = Color("themeFinishesSilverDialDark", bundle: .main)
    /// `#F4F5F1` — `themeFinishes.silver.dialLight`
    public static let themeFinishesSilverDialLight = Color("themeFinishesSilverDialLight", bundle: .main)
    /// `#0F1113` — `themeFinishes.silver.fieldDark`
    public static let themeFinishesSilverFieldDark = Color("themeFinishesSilverFieldDark", bundle: .main)
    /// `#E8EAE7` — `themeFinishes.silver.fieldLight`
    public static let themeFinishesSilverFieldLight = Color("themeFinishesSilverFieldLight", bundle: .main)
    /// `#E0E3DF` — `themeFinishes.silver.wellLight`
    public static let themeFinishesSilverWellLight = Color("themeFinishesSilverWellLight", bundle: .main)
    /// `#161B1E` — `themeFinishes.slate.dialDark`
    public static let themeFinishesSlateDialDark = Color("themeFinishesSlateDialDark", bundle: .main)
    /// `#EFF2F3` — `themeFinishes.slate.dialLight`
    public static let themeFinishesSlateDialLight = Color("themeFinishesSlateDialLight", bundle: .main)
    /// `#0E1214` — `themeFinishes.slate.fieldDark`
    public static let themeFinishesSlateFieldDark = Color("themeFinishesSlateFieldDark", bundle: .main)
    /// `#E0E4E6` — `themeFinishes.slate.fieldLight`
    public static let themeFinishesSlateFieldLight = Color("themeFinishesSlateFieldLight", bundle: .main)
    /// `#D8DDE0` — `themeFinishes.slate.wellLight`
    public static let themeFinishesSlateWellLight = Color("themeFinishesSlateWellLight", bundle: .main)
}
